In [ ]:
print('Name: Ethan Nguyen')
print('Create a GUI to read any CSV, clean the data, and create widgets to select the column names, and graph type')

In [1]:
#pre defined code
from ipywidgets import widgets
from IPython.display import display, clear_output
import pandas as pd
from tkinter import Tk, filedialog
import matplotlib.pyplot as plt 
import numpy as np

graph_type = ['Choose one..', 'bubble', 'bar']
funtionality = ['Choose One', 'Sort', 'Filter']
sort_option = ['ascending', 'descending']
df = ''
new_df = ''
input_box = ''
input_fontsize = ''
input_title = ''


def select_files(b):
    clear_output() 
    global df
    root = Tk()
    root.withdraw() 
    file_name = filedialog.askopenfilename() 
    df = pd.read_csv(file_name)
    function_widget = widgets.Dropdown(options=funtionality)
    function_int = widgets.interactive(choose_the_function, function=function_widget)
    display(function_int)
    
def choose_the_function(function):
    global sort_option
    global df
    global input_box
    if(function == 'Sort'):
        sort_col_widget = widgets.Dropdown(options=df.columns)
        sort_option_widget = widgets.Dropdown(options = sort_option)
        range_widget = widgets.Dropdown(options = [20,30,40])
        sort_int = widgets.interactive(sort_dataframe, column=sort_col_widget, type_of_sort= sort_option_widget, head_range=range_widget)
        display(sort_int)
    elif(function == 'Filter'):
        display(df)
        input_box = widgets.Text(description='Value:')
        display(input_box)
        filter_col_widget = widgets.Dropdown(options=df.columns)
        compare_widget = widgets.Dropdown(options = ['Choose the option..','=', '>','<'])
        head=widgets.Dropdown(options = [20,30,40])
        groupby_int = widgets.interactive(filter_dataframe, filter_column=filter_col_widget, comparison= compare_widget,head_df=head)
        display(groupby_int)
    else:
        print('Choose a function')
        
def sort_dataframe(column, type_of_sort,head_range):
    global df
    global new_df
    try:
        print(df[column].dtypes)
        if(df[column].dtypes != 'float' or df[column].dtypes != 'int'):
            df[column] = df[column].astype(float)
        if(type_of_sort == 'ascending'):
            new_df = df.sort_values(column, ascending=True)
            display(new_df)
        else:
            new_df = df.sort_values(column, ascending=False)
            display(new_df)
        new_df = new_df.head(head_range)
        get_widget()
    except:
        print('The data is not structured so cannot perform the selected action')
        
#End code done in project C200

def filter_dataframe(filter_column, comparison,head_df):
    print("filter_dataframe")
    global df
    global new_df
    global input_box
    if(comparison == '='):
        new_df = df.loc[df[filter_column] == input_box.value]
        new_df=new_df.head(head_df)
        display(new_df)
    elif(comparison == '>'):
        new_df = df.loc[df[filter_column] > int(input_box.value)]
        new_df=new_df.head(head_df)
        display(new_df)
    elif(comparison == '>'):
        new_df = df.loc[df[filter_column] > int(input_box.value)]
        new_df=new_df.head(head_df)
        display(new_df)
    else:
        print('Choose correct option')
    get_widget()
    
def get_widget():
    print("get_widget")

/Users/ethangamer/Downloads/ADV-C200-Student/cardiovascular.csv

,Unnamed: 0,id,age,gender,height,weight,systolic_blood_pressure,diastolic_blood_pressure,cholesterol,gluc,smoke,alco,active,cardio
0,0,0,50.0,2,168,62.0,110,80,1,1,0,0,1,0
1,1,1,55.0,1,156,85.0,140,90,3,1,0,0,1,1
2,2,2,51.0,1,165,64.0,130,70,3,1,0,0,0,1
3,3,3,48.0,2,169,82.0,150,100,1,1,0,0,1,1
4,4,4,47.0,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,69995,99993,52.0,2,168,76.0,120,80,1,1,1,0,1,0
69996,69996,99995,61.0,1,158,126.0,140,90,2,2,0,0,1,1
69997,69997,99996,52.0,2,183,105.0,180,90,3,1,0,1,0,1
69998,69998,99998,61.0,1,163,72.0,135,80,1,2,0,0,0,1
69999,69999,99999,56.0,1,170,72.0,120,80,2,1,0,0,1,0

interactive(children=(Dropdown(description='groupby_column', options=('Unnamed: 0', 'id', 'age', 'gender', 'heâ€¦